source 'https://github.com/CocoaPods/Specs.git'

target 'GCountableUILabel', :exclusive => true do
  pod "GCountableUILabel", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "GCountableUILabel", :path => "../"

  
end
